export type RecommendedBook = {
  title: string
  author: string
  lang: 'ko' | 'en'
  emoji: string
}

export const RECOMMENDED_BOOKS: Record<string, RecommendedBook[]> = {
  K: [
    { title: '강아지똥', author: '권정생', lang: 'ko', emoji: '🐶' },
    { title: '100층짜리 집', author: '이와이 도시오', lang: 'ko', emoji: '🏠' },
    { title: '구름빵', author: '백희나', lang: 'ko', emoji: '☁️' },
    { title: '달 샤베트', author: '백희나', lang: 'ko', emoji: '🌙' },
    { title: '으뜸 헤엄이', author: '레오 리오니', lang: 'ko', emoji: '🐟' },
    { title: '곰 사냥을 떠나자', author: '마이클 로젠', lang: 'ko', emoji: '🐻' },
    { title: '팥죽 할멈과 호랑이', author: '전래동화', lang: 'ko', emoji: '🐯' },
    { title: '흥부와 놀부', author: '전래동화', lang: 'ko', emoji: '🦅' },
    { title: '아씨방 일곱 동무', author: '이영경', lang: 'ko', emoji: '🧵' },
    { title: '빨간 부채 파란 부채', author: '전래동화', lang: 'ko', emoji: '🪭' },
    { title: 'The Very Hungry Caterpillar', author: 'Eric Carle', lang: 'en', emoji: '🐛' },
    { title: 'Goodnight Moon', author: 'Margaret Wise Brown', lang: 'en', emoji: '🌕' },
    { title: 'Where the Wild Things Are', author: 'Maurice Sendak', lang: 'en', emoji: '👹' },
    { title: 'The Snowy Day', author: 'Ezra Jack Keats', lang: 'en', emoji: '❄️' },
    { title: 'Green Eggs and Ham', author: 'Dr. Seuss', lang: 'en', emoji: '🍳' },
    { title: 'Corduroy', author: 'Don Freeman', lang: 'en', emoji: '🧸' },
    { title: 'If You Give a Mouse a Cookie', author: 'Laura Numeroff', lang: 'en', emoji: '🍪' },
    { title: 'The Giving Tree', author: 'Shel Silverstein', lang: 'en', emoji: '🌳' },
    { title: 'Brown Bear, Brown Bear', author: 'Bill Martin Jr.', lang: 'en', emoji: '🐻' },
    { title: 'Chicka Chicka Boom Boom', author: 'Bill Martin Jr.', lang: 'en', emoji: '🌴' },
  ],
  '1': [
    { title: '마당을 나온 암탉', author: '황선미', lang: 'ko', emoji: '🐔' },
    { title: '내 이름은 삐삐 롱스타킹', author: '아스트리드 린드그렌', lang: 'ko', emoji: '👧' },
    { title: '손 큰 할머니의 만두 만들기', author: '채인선', lang: 'ko', emoji: '🥟' },
    { title: '책 먹는 여우', author: '프란치스카 비어만', lang: 'ko', emoji: '🦊' },
    { title: '거인의 정원', author: '오스카 와일드', lang: 'ko', emoji: '🌸' },
    { title: '개구리와 두꺼비는 친구', author: '아놀드 로벨', lang: 'ko', emoji: '🐸' },
    { title: '사랑해 사랑해 사랑해', author: '버나뎃 로제티 슈스탁', lang: 'ko', emoji: '❤️' },
    { title: '해님 달님', author: '전래동화', lang: 'ko', emoji: '☀️' },
    { title: '토끼와 거북이', author: '이솝', lang: 'ko', emoji: '🐢' },
    { title: '수박 수영장', author: '안녕달', lang: 'ko', emoji: '🍉' },
    { title: 'Frog and Toad Are Friends', author: 'Arnold Lobel', lang: 'en', emoji: '🐸' },
    { title: "Charlotte's Web", author: 'E.B. White', lang: 'en', emoji: '🕷️' },
    { title: 'The Cat in the Hat', author: 'Dr. Seuss', lang: 'en', emoji: '🐱' },
    { title: 'Amelia Bedelia', author: 'Peggy Parish', lang: 'en', emoji: '🧹' },
    { title: 'Magic Tree House #1', author: 'Mary Pope Osborne', lang: 'en', emoji: '🦕' },
    { title: 'Henry and Mudge', author: 'Cynthia Rylant', lang: 'en', emoji: '🐕' },
    { title: 'Nate the Great', author: 'Marjorie Weinman Sharmat', lang: 'en', emoji: '🔍' },
    { title: 'The Berenstain Bears', author: 'Stan & Jan Berenstain', lang: 'en', emoji: '🐻' },
    { title: 'Elephant and Piggie', author: 'Mo Willems', lang: 'en', emoji: '🐘' },
    { title: 'Little Bear', author: 'Else Holmelund Minarik', lang: 'en', emoji: '🐻' },
  ],
  '2': [
    { title: '아낌없이 주는 나무', author: '쉘 실버스타인', lang: 'ko', emoji: '🌲' },
    { title: '어린 왕자', author: '생텍쥐페리', lang: 'ko', emoji: '🌹' },
    { title: '피노키오', author: '카를로 콜로디', lang: 'ko', emoji: '🤥' },
    { title: '이상한 나라의 앨리스', author: '루이스 캐럴', lang: 'ko', emoji: '🐇' },
    { title: '오즈의 마법사', author: '프랭크 바움', lang: 'ko', emoji: '🌈' },
    { title: '빨간 머리 앤', author: '루시 모드 몽고메리', lang: 'ko', emoji: '👩‍🦰' },
    { title: '꼬마 마녀', author: '오트프리트 프로이슬러', lang: 'ko', emoji: '🧙‍♀️' },
    { title: '비밀의 화원', author: '프랜시스 버넷', lang: 'ko', emoji: '🌺' },
    { title: '소공자', author: '프랜시스 버넷', lang: 'ko', emoji: '🎩' },
    { title: '101마리 달마시안', author: '도디 스미스', lang: 'ko', emoji: '🐕' },
    { title: 'Stuart Little', author: 'E.B. White', lang: 'en', emoji: '🐭' },
    { title: 'The Boxcar Children', author: 'Gertrude Chandler Warner', lang: 'en', emoji: '🚂' },
    { title: "My Father's Dragon", author: 'Ruth Stiles Gannett', lang: 'en', emoji: '🐉' },
    { title: 'Ramona the Pest', author: 'Beverly Cleary', lang: 'en', emoji: '🎒' },
    { title: 'James and the Giant Peach', author: 'Roald Dahl', lang: 'en', emoji: '🍑' },
    { title: 'Sideways Stories from Wayside School', author: 'Louis Sachar', lang: 'en', emoji: '🏫' },
    { title: 'The Mouse and the Motorcycle', author: 'Beverly Cleary', lang: 'en', emoji: '🏍️' },
    { title: 'Encyclopedia Brown', author: 'Donald J. Sobol', lang: 'en', emoji: '📚' },
    { title: 'Freckle Juice', author: 'Judy Blume', lang: 'en', emoji: '🥤' },
    { title: 'The Phantom Tollbooth', author: 'Norton Juster', lang: 'en', emoji: '🔔' },
  ],
  '3': [
    { title: '초정리 편지', author: '배유안', lang: 'ko', emoji: '✉️' },
    { title: '나쁜 어린이 표', author: '황선미', lang: 'ko', emoji: '🏷️' },
    { title: '꽃들에게 희망을', author: '트리나 폴러스', lang: 'ko', emoji: '🦋' },
    { title: '행복한 왕자', author: '오스카 와일드', lang: 'ko', emoji: '👑' },
    { title: '플랜더스의 개', author: '위다', lang: 'ko', emoji: '🐩' },
    { title: '하멜른의 피리 부는 사나이', author: '그림 형제', lang: 'ko', emoji: '🎶' },
    { title: '돌멩이 수프', author: '마르나 브라운', lang: 'ko', emoji: '🍲' },
    { title: '우리 선생님이 최고야!', author: '케빈 헹크스', lang: 'ko', emoji: '👩‍🏫' },
    { title: '오세암', author: '정채봉', lang: 'ko', emoji: '⛩️' },
    { title: '나무는 좋다', author: '재니스 메이 우드리', lang: 'ko', emoji: '🌳' },
    { title: 'Charlie and the Chocolate Factory', author: 'Roald Dahl', lang: 'en', emoji: '🍫' },
    { title: 'The Cricket in Times Square', author: 'George Selden', lang: 'en', emoji: '🦗' },
    { title: 'Harriet the Spy', author: 'Louise Fitzhugh', lang: 'en', emoji: '🕵️' },
    { title: 'Holes', author: 'Louis Sachar', lang: 'en', emoji: '⛏️' },
    { title: 'The One and Only Ivan', author: 'Katherine Applegate', lang: 'en', emoji: '🦍' },
    { title: 'Because of Winn-Dixie', author: 'Kate DiCamillo', lang: 'en', emoji: '🐶' },
    { title: 'Sarah, Plain and Tall', author: 'Patricia MacLachlan', lang: 'en', emoji: '🌾' },
    { title: "Mr. Popper's Penguins", author: 'Richard & Florence Atwater', lang: 'en', emoji: '🐧' },
    { title: 'The Trumpet of the Swan', author: 'E.B. White', lang: 'en', emoji: '🦢' },
    { title: 'Island of the Blue Dolphins', author: "Scott O'Dell", lang: 'en', emoji: '🐬' },
  ],
  '4': [
    { title: '봄봄', author: '김유정', lang: 'ko', emoji: '🌸' },
    { title: '소나기', author: '황순원', lang: 'ko', emoji: '🌧️' },
    { title: '별 헤는 밤', author: '윤동주', lang: 'ko', emoji: '⭐' },
    { title: '15소년 표류기', author: '쥘 베른', lang: 'ko', emoji: '🏝️' },
    { title: '걸리버 여행기', author: '조너선 스위프트', lang: 'ko', emoji: '🧭' },
    { title: '로빈슨 크루소', author: '대니얼 디포', lang: 'ko', emoji: '🌴' },
    { title: '보물섬', author: '로버트 루이스 스티븐슨', lang: 'ko', emoji: '💎' },
    { title: '삼총사', author: '알렉상드르 뒤마', lang: 'ko', emoji: '🗡️' },
    { title: '시튼 동물기', author: '어니스트 톰프슨 시튼', lang: 'ko', emoji: '🐺' },
    { title: '열두 살에 부자가 된 키라', author: '보도 섀퍼', lang: 'ko', emoji: '💰' },
    { title: 'The Giver', author: 'Lois Lowry', lang: 'en', emoji: '🎁' },
    { title: 'Tuck Everlasting', author: 'Natalie Babbitt', lang: 'en', emoji: '💧' },
    { title: 'Number the Stars', author: 'Lois Lowry', lang: 'en', emoji: '✡️' },
    { title: 'Bridge to Terabithia', author: 'Katherine Paterson', lang: 'en', emoji: '🌉' },
    { title: "Mrs. Frisby and the Rats of NIMH", author: "Robert C. O'Brien", lang: 'en', emoji: '🐀' },
    { title: 'A Wrinkle in Time', author: "Madeleine L'Engle", lang: 'en', emoji: '⏳' },
    { title: 'Little Women', author: 'Louisa May Alcott', lang: 'en', emoji: '👩‍👧' },
    { title: 'The Wind in the Willows', author: 'Kenneth Grahame', lang: 'en', emoji: '🌊' },
    { title: 'The Call of the Wild', author: 'Jack London', lang: 'en', emoji: '🐺' },
    { title: 'Swiss Family Robinson', author: 'Johann David Wyss', lang: 'en', emoji: '🏕️' },
  ],
  '5': [
    { title: '동백꽃', author: '김유정', lang: 'ko', emoji: '🌺' },
    { title: '메밀꽃 필 무렵', author: '이효석', lang: 'ko', emoji: '🌾' },
    { title: '운수 좋은 날', author: '현진건', lang: 'ko', emoji: '🚗' },
    { title: '톰 소여의 모험', author: '마크 트웨인', lang: 'ko', emoji: '🚣' },
    { title: '허클베리 핀의 모험', author: '마크 트웨인', lang: 'ko', emoji: '🛶' },
    { title: '80일간의 세계일주', author: '쥘 베른', lang: 'ko', emoji: '✈️' },
    { title: '해저 2만리', author: '쥘 베른', lang: 'ko', emoji: '🐙' },
    { title: '나니아 연대기 1', author: 'C.S. 루이스', lang: 'ko', emoji: '🦁' },
    { title: '해리포터와 마법사의 돌', author: 'J.K. 롤링', lang: 'ko', emoji: '⚡' },
    { title: '몽실 언니', author: '권정생', lang: 'ko', emoji: '👧' },
    { title: 'Hatchet', author: 'Gary Paulsen', lang: 'en', emoji: '🪓' },
    { title: 'The Outsiders', author: 'S.E. Hinton', lang: 'en', emoji: '🌅' },
    { title: 'Where the Red Fern Grows', author: 'Wilson Rawls', lang: 'en', emoji: '🐕' },
    { title: 'My Side of the Mountain', author: 'Jean Craighead George', lang: 'en', emoji: '⛰️' },
    { title: 'Bud, Not Buddy', author: 'Christopher Paul Curtis', lang: 'en', emoji: '🎺' },
    { title: 'Walk Two Moons', author: 'Sharon Creech', lang: 'en', emoji: '🌕' },
    { title: 'Roll of Thunder, Hear My Cry', author: 'Mildred D. Taylor', lang: 'en', emoji: '⛈️' },
    { title: 'Anne of Green Gables', author: 'L.M. Montgomery', lang: 'en', emoji: '🏡' },
    { title: 'The Secret Garden', author: 'Frances Hodgson Burnett', lang: 'en', emoji: '🌹' },
    { title: "Harry Potter and the Sorcerer's Stone", author: 'J.K. Rowling', lang: 'en', emoji: '🧙' },
  ],
  '6': [
    { title: '무진기행', author: '김승옥', lang: 'ko', emoji: '🌫️' },
    { title: '난쟁이가 쏘아올린 작은 공', author: '조세희', lang: 'ko', emoji: '⚽' },
    { title: '장마', author: '윤흥길', lang: 'ko', emoji: '🌧️' },
    { title: '수난이대', author: '하근찬', lang: 'ko', emoji: '🎖️' },
    { title: '젊은 느티나무', author: '강신재', lang: 'ko', emoji: '🌳' },
    { title: '파친코', author: '이민진', lang: 'ko', emoji: '🎰' },
    { title: '상록수', author: '심훈', lang: 'ko', emoji: '🌿' },
    { title: '사랑손님과 어머니', author: '주요섭', lang: 'ko', emoji: '💌' },
    { title: '오발탄', author: '이범선', lang: 'ko', emoji: '💥' },
    { title: '삼대', author: '염상섭', lang: 'ko', emoji: '👨‍👩‍👦' },
    { title: 'The Hobbit', author: 'J.R.R. Tolkien', lang: 'en', emoji: '🧙' },
    { title: 'Treasure Island', author: 'Robert Louis Stevenson', lang: 'en', emoji: '🗺️' },
    { title: 'Watership Down', author: 'Richard Adams', lang: 'en', emoji: '🐰' },
    { title: 'Johnny Tremain', author: 'Esther Forbes', lang: 'en', emoji: '🏺' },
    { title: 'Across Five Aprils', author: 'Irene Hunt', lang: 'en', emoji: '🌷' },
    { title: "Julie of the Wolves", author: 'Jean Craighead George', lang: 'en', emoji: '🐺' },
    { title: "The True Confessions of Charlotte Doyle", author: 'Avi', lang: 'en', emoji: '⛵' },
    { title: 'The Witch of Blackbird Pond', author: 'Elizabeth George Speare', lang: 'en', emoji: '🧙‍♀️' },
    { title: 'The Bronze Bow', author: 'Elizabeth George Speare', lang: 'en', emoji: '🏹' },
    { title: 'The Cay', author: 'Theodore Taylor', lang: 'en', emoji: '🏝️' },
  ],
  '7': [
    { title: '완득이', author: '김려령', lang: 'ko', emoji: '🥊' },
    { title: '82년생 김지영', author: '조남주', lang: 'ko', emoji: '👩‍💼' },
    { title: '엄마를 부탁해', author: '신경숙', lang: 'ko', emoji: '👩' },
    { title: '채식주의자', author: '한강', lang: 'ko', emoji: '🥦' },
    { title: '무녀도', author: '김동리', lang: 'ko', emoji: '🔮' },
    { title: '역마', author: '김동리', lang: 'ko', emoji: '🐴' },
    { title: '황진이', author: '홍석중', lang: 'ko', emoji: '🌙' },
    { title: '광장', author: '최인훈', lang: 'ko', emoji: '🏛️' },
    { title: '데미안', author: '헤르만 헤세', lang: 'ko', emoji: '🦅' },
    { title: '싯다르타', author: '헤르만 헤세', lang: 'ko', emoji: '🧘' },
    { title: 'The Diary of a Young Girl', author: 'Anne Frank', lang: 'en', emoji: '📔' },
    { title: 'To Kill a Mockingbird', author: 'Harper Lee', lang: 'en', emoji: '🐦' },
    { title: 'The Catcher in the Rye', author: 'J.D. Salinger', lang: 'en', emoji: '🧢' },
    { title: 'Lord of the Flies', author: 'William Golding', lang: 'en', emoji: '🪰' },
    { title: 'Animal Farm', author: 'George Orwell', lang: 'en', emoji: '🐷' },
    { title: 'A Separate Peace', author: 'John Knowles', lang: 'en', emoji: '🌿' },
    { title: 'The House on Mango Street', author: 'Sandra Cisneros', lang: 'en', emoji: '🏠' },
    { title: 'Black Boy', author: 'Richard Wright', lang: 'en', emoji: '✊' },
    { title: 'My Antonia', author: 'Willa Cather', lang: 'en', emoji: '🌻' },
    { title: 'A Raisin in the Sun', author: 'Lorraine Hansberry', lang: 'en', emoji: '☀️' },
  ],
  '8': [
    { title: '홍길동전', author: '허균', lang: 'ko', emoji: '🦸' },
    { title: '춘향전', author: '작자 미상', lang: 'ko', emoji: '💃' },
    { title: '심청전', author: '작자 미상', lang: 'ko', emoji: '👁️' },
    { title: '구운몽', author: '김만중', lang: 'ko', emoji: '💭' },
    { title: '양반전', author: '박지원', lang: 'ko', emoji: '🎭' },
    { title: '무정', author: '이광수', lang: 'ko', emoji: '💔' },
    { title: '날개', author: '이상', lang: 'ko', emoji: '🪶' },
    { title: '탁류', author: '채만식', lang: 'ko', emoji: '🌊' },
    { title: '인간문제', author: '강경애', lang: 'ko', emoji: '🏭' },
    { title: '태평천하', author: '채만식', lang: 'ko', emoji: '🌏' },
    { title: 'Romeo and Juliet', author: 'William Shakespeare', lang: 'en', emoji: '💕' },
    { title: 'Great Expectations', author: 'Charles Dickens', lang: 'en', emoji: '🎩' },
    { title: 'Fahrenheit 451', author: 'Ray Bradbury', lang: 'en', emoji: '🔥' },
    { title: '1984', author: 'George Orwell', lang: 'en', emoji: '👁️' },
    { title: 'Of Mice and Men', author: 'John Steinbeck', lang: 'en', emoji: '🐭' },
    { title: 'The Old Man and the Sea', author: 'Ernest Hemingway', lang: 'en', emoji: '🎣' },
    { title: 'Brave New World', author: 'Aldous Huxley', lang: 'en', emoji: '🧬' },
    { title: 'The Red Badge of Courage', author: 'Stephen Crane', lang: 'en', emoji: '🎖️' },
    { title: 'Their Eyes Were Watching God', author: 'Zora Neale Hurston', lang: 'en', emoji: '👁️' },
    { title: 'Death of a Salesman', author: 'Arthur Miller', lang: 'en', emoji: '💼' },
  ],
  '9': [
    { title: '페스트', author: '알베르 카뮈', lang: 'ko', emoji: '🦠' },
    { title: '이방인', author: '알베르 카뮈', lang: 'ko', emoji: '🌞' },
    { title: '죄와 벌', author: '도스토예프스키', lang: 'ko', emoji: '⚖️' },
    { title: '카라마조프가의 형제들', author: '도스토예프스키', lang: 'ko', emoji: '👨‍👦' },
    { title: '전쟁과 평화', author: '톨스토이', lang: 'ko', emoji: '⚔️' },
    { title: '안나 카레니나', author: '톨스토이', lang: 'ko', emoji: '🚂' },
    { title: '수레바퀴 아래서', author: '헤르만 헤세', lang: 'ko', emoji: '🎡' },
    { title: '고독의 백년', author: '가르시아 마르케스', lang: 'ko', emoji: '🦋' },
    { title: '변신', author: '프란츠 카프카', lang: 'ko', emoji: '🪲' },
    { title: '구토', author: '장폴 사르트르', lang: 'ko', emoji: '🤢' },
    { title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', lang: 'en', emoji: '🥂' },
    { title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne', lang: 'en', emoji: '🔴' },
    { title: 'Frankenstein', author: 'Mary Shelley', lang: 'en', emoji: '⚡' },
    { title: 'Jane Eyre', author: 'Charlotte Brontë', lang: 'en', emoji: '🌙' },
    { title: 'Wuthering Heights', author: 'Emily Brontë', lang: 'en', emoji: '🌪️' },
    { title: 'Pride and Prejudice', author: 'Jane Austen', lang: 'en', emoji: '💍' },
    { title: 'The Crucible', author: 'Arthur Miller', lang: 'en', emoji: '🔥' },
    { title: 'Beloved', author: 'Toni Morrison', lang: 'en', emoji: '👻' },
    { title: 'The Sun Also Rises', author: 'Ernest Hemingway', lang: 'en', emoji: '🌅' },
    { title: 'A Farewell to Arms', author: 'Ernest Hemingway', lang: 'en', emoji: '🎖️' },
  ],
  '10': [
    { title: '허생전', author: '박지원', lang: 'ko', emoji: '💰' },
    { title: '열하일기', author: '박지원', lang: 'ko', emoji: '📖' },
    { title: '목민심서', author: '정약용', lang: 'ko', emoji: '🏛️' },
    { title: '임꺽정', author: '홍명희', lang: 'ko', emoji: '🦸' },
    { title: '아리랑', author: '조정래', lang: 'ko', emoji: '🎵' },
    { title: '태백산맥', author: '조정래', lang: 'ko', emoji: '⛰️' },
    { title: '토지', author: '박경리', lang: 'ko', emoji: '🌾' },
    { title: '나목', author: '박완서', lang: 'ko', emoji: '🌿' },
    { title: '그 많던 싱아는 누가 다 먹었을까', author: '박완서', lang: 'ko', emoji: '🍃' },
    { title: 'AQ정전', author: '루쉰', lang: 'ko', emoji: '🎭' },
    { title: 'Hamlet', author: 'William Shakespeare', lang: 'en', emoji: '💀' },
    { title: 'Macbeth', author: 'William Shakespeare', lang: 'en', emoji: '🗡️' },
    { title: 'Othello', author: 'William Shakespeare', lang: 'en', emoji: '🎭' },
    { title: 'The Merchant of Venice', author: 'William Shakespeare', lang: 'en', emoji: '⚖️' },
    { title: "A Midsummer Night's Dream", author: 'William Shakespeare', lang: 'en', emoji: '🧚' },
    { title: 'Beowulf', author: 'Anonymous', lang: 'en', emoji: '🐉' },
    { title: "Gulliver's Travels", author: 'Jonathan Swift', lang: 'en', emoji: '🧭' },
    { title: 'Robinson Crusoe', author: 'Daniel Defoe', lang: 'en', emoji: '🏝️' },
    { title: 'Moby-Dick', author: 'Herman Melville', lang: 'en', emoji: '🐋' },
    { title: 'The Sound and the Fury', author: 'William Faulkner', lang: 'en', emoji: '🌊' },
  ],
  '11': [
    { title: '인간의 굴레에서', author: '서머싯 몸', lang: 'ko', emoji: '⛓️' },
    { title: '닥터 지바고', author: '보리스 파스테르나크', lang: 'ko', emoji: '❄️' },
    { title: '지하생활자의 수기', author: '도스토예프스키', lang: 'ko', emoji: '🕳️' },
    { title: '삼국유사', author: '일연', lang: 'ko', emoji: '📜' },
    { title: '조선왕조실록', author: '편찬위원회', lang: 'ko', emoji: '📚' },
    { title: '흠흠신서', author: '정약용', lang: 'ko', emoji: '⚖️' },
    { title: '소년이 온다', author: '한강', lang: 'ko', emoji: '✊' },
    { title: '아몬드', author: '손원평', lang: 'ko', emoji: '🌰' },
    { title: '7년의 밤', author: '정유정', lang: 'ko', emoji: '🌌' },
    { title: '살인자의 기억법', author: '김영하', lang: 'ko', emoji: '🔪' },
    { title: 'The Iliad', author: 'Homer', lang: 'en', emoji: '🛡️' },
    { title: 'The Odyssey', author: 'Homer', lang: 'en', emoji: '⚓' },
    { title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', lang: 'en', emoji: '🔪' },
    { title: 'As I Lay Dying', author: 'William Faulkner', lang: 'en', emoji: '🌿' },
    { title: 'Invisible Man', author: 'Ralph Ellison', lang: 'en', emoji: '🫥' },
    { title: 'The Trial', author: 'Franz Kafka', lang: 'en', emoji: '🏛️' },
    { title: 'Mrs. Dalloway', author: 'Virginia Woolf', lang: 'en', emoji: '🌸' },
    { title: 'Paradise Lost', author: 'John Milton', lang: 'en', emoji: '👿' },
    { title: 'Don Quixote', author: 'Miguel de Cervantes', lang: 'en', emoji: '⚔️' },
    { title: 'Inferno', author: 'Dante Alighieri', lang: 'en', emoji: '🔥' },
  ],
  '12': [
    { title: '무정', author: '이광수', lang: 'ko', emoji: '💔' },
    { title: '혈의 누', author: '이인직', lang: 'ko', emoji: '🩸' },
    { title: '금수회의록', author: '안국선', lang: 'ko', emoji: '🐾' },
    { title: '만세전', author: '염상섭', lang: 'ko', emoji: '✊' },
    { title: '카인의 후예', author: '황순원', lang: 'ko', emoji: '🌑' },
    { title: '화수분', author: '전영택', lang: 'ko', emoji: '🫙' },
    { title: '두 파산', author: '염상섭', lang: 'ko', emoji: '💸' },
    { title: '레디메이드 인생', author: '채만식', lang: 'ko', emoji: '💼' },
    { title: '봉별기', author: '이상', lang: 'ko', emoji: '✒️' },
    { title: '표본실의 청개구리', author: '염상섭', lang: 'ko', emoji: '🐸' },
    { title: 'Ulysses', author: 'James Joyce', lang: 'en', emoji: '🌀' },
    { title: 'In Search of Lost Time', author: 'Marcel Proust', lang: 'en', emoji: '⏰' },
    { title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky', lang: 'en', emoji: '⛪' },
    { title: 'Faust', author: 'Johann Wolfgang von Goethe', lang: 'en', emoji: '😈' },
    { title: 'War and Peace', author: 'Leo Tolstoy', lang: 'en', emoji: '🏰' },
    { title: 'Canterbury Tales', author: 'Geoffrey Chaucer', lang: 'en', emoji: '🏰' },
    { title: 'Anna Karenina', author: 'Leo Tolstoy', lang: 'en', emoji: '🚂' },
    { title: 'Middlemarch', author: 'George Eliot', lang: 'en', emoji: '🏘️' },
    { title: 'Bleak House', author: 'Charles Dickens', lang: 'en', emoji: '🌫️' },
    { title: 'To the Lighthouse', author: 'Virginia Woolf', lang: 'en', emoji: '🏮' },
  ],
  adult: [
    { title: '채식주의자', author: '한강', lang: 'ko', emoji: '🌿' },
    { title: '소년이 온다', author: '한강', lang: 'ko', emoji: '✊' },
    { title: '아몬드', author: '손원평', lang: 'ko', emoji: '🌰' },
    { title: '82년생 김지영', author: '조남주', lang: 'ko', emoji: '👩' },
    { title: '7년의 밤', author: '정유정', lang: 'ko', emoji: '🌌' },
    { title: '종의 기원', author: '정유정', lang: 'ko', emoji: '🧬' },
    { title: '살인자의 기억법', author: '김영하', lang: 'ko', emoji: '🔪' },
    { title: '나는 나를 파괴할 권리가 있다', author: '김영하', lang: 'ko', emoji: '💔' },
    { title: '파친코', author: '이민진', lang: 'ko', emoji: '🎰' },
    { title: '흰', author: '한강', lang: 'ko', emoji: '🤍' },
    { title: 'Sapiens', author: 'Yuval Noah Harari', lang: 'en', emoji: '🦴' },
    { title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', lang: 'en', emoji: '🧠' },
    { title: 'Atomic Habits', author: 'James Clear', lang: 'en', emoji: '⚛️' },
    { title: "Man's Search for Meaning", author: 'Viktor E. Frankl', lang: 'en', emoji: '🕯️' },
    { title: 'The Alchemist', author: 'Paulo Coelho', lang: 'en', emoji: '⚗️' },
    { title: 'Gone with the Wind', author: 'Margaret Mitchell', lang: 'en', emoji: '🌪️' },
    { title: 'The Road', author: 'Cormac McCarthy', lang: 'en', emoji: '🛣️' },
    { title: 'Educated', author: 'Tara Westover', lang: 'en', emoji: '📚' },
    { title: 'The Power of Habit', author: 'Charles Duhigg', lang: 'en', emoji: '🔄' },
    { title: 'Becoming', author: 'Michelle Obama', lang: 'en', emoji: '👑' },
  ],
}
